/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppCliente.vista;

import AppCliente.modelo.Cliente;
import general.Peticion;
import general.TAccion;

/**
 *
 * @author Javier
 */
public class FrmPantallaPrincipalAdm extends javax.swing.JFrame {

    /**
     * Creates new form FrmPantallaPrincipalAdm
     */
    public FrmPantallaPrincipalAdm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonModificarProducto = new javax.swing.JButton();
        jButtonEliminarProducto = new javax.swing.JButton();
        jButtonAgregarProducto = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cargarPedidosBtt = new javax.swing.JButton();
        salirBtt = new javax.swing.JButton();
        nomUsuario = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        agregarProductoBtt = new javax.swing.JButton();
        modificarProductoBtt = new javax.swing.JButton();
        eliminarCatalogoBtt = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        nuncaPedidosBtt1 = new javax.swing.JButton();
        verTopTenBtt1 = new javax.swing.JButton();
        distribucionPedidosBtt1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pedidosLista = new javax.swing.JTextArea();

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 20)); // NOI18N
        jLabel1.setText("Configuraciones del catálogo");

        jButtonModificarProducto.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 12)); // NOI18N
        jButtonModificarProducto.setText("Modificar producto");

        jButtonEliminarProducto.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 12)); // NOI18N
        jButtonEliminarProducto.setText("Eliminar producto");
        jButtonEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarProductoActionPerformed(evt);
            }
        });

        jButtonAgregarProducto.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 12)); // NOI18N
        jButtonAgregarProducto.setText("Agregar producto");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(195, 226, 203));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 22)); // NOI18N
        jLabel2.setText("Pedidos realizados:");

        cargarPedidosBtt.setBackground(new java.awt.Color(108, 145, 108));
        cargarPedidosBtt.setText("Cargar pedidos");
        cargarPedidosBtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarPedidosBttActionPerformed(evt);
            }
        });

        salirBtt.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        salirBtt.setText("Salir");
        salirBtt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirBttMouseClicked(evt);
            }
        });
        salirBtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirBttActionPerformed(evt);
            }
        });

        nomUsuario.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 12)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 22)); // NOI18N
        jLabel3.setText("Configuraciones del catálogo");

        agregarProductoBtt.setBackground(new java.awt.Color(108, 145, 108));
        agregarProductoBtt.setText("Agregar producto");
        agregarProductoBtt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarProductoBttMouseClicked(evt);
            }
        });
        agregarProductoBtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarProductoBttActionPerformed(evt);
            }
        });

        modificarProductoBtt.setBackground(new java.awt.Color(108, 145, 108));
        modificarProductoBtt.setText("Modificar producto");
        modificarProductoBtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarProductoBttActionPerformed(evt);
            }
        });

        eliminarCatalogoBtt.setBackground(new java.awt.Color(108, 145, 108));
        eliminarCatalogoBtt.setText("Eliminar producto");
        eliminarCatalogoBtt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eliminarCatalogoBttMouseClicked(evt);
            }
        });
        eliminarCatalogoBtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarCatalogoBttActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(modificarProductoBtt, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eliminarCatalogoBtt)
                            .addComponent(agregarProductoBtt, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel3)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(33, 33, 33)
                .addComponent(agregarProductoBtt)
                .addGap(29, 29, 29)
                .addComponent(modificarProductoBtt)
                .addGap(18, 18, 18)
                .addComponent(eliminarCatalogoBtt)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 22)); // NOI18N
        jLabel4.setText("Estadísticas");

        nuncaPedidosBtt1.setBackground(new java.awt.Color(108, 145, 108));
        nuncaPedidosBtt1.setText("Ver nunca pedidos");

        verTopTenBtt1.setBackground(new java.awt.Color(108, 145, 108));
        verTopTenBtt1.setText("Ver Top Ten");

        distribucionPedidosBtt1.setBackground(new java.awt.Color(108, 145, 108));
        distribucionPedidosBtt1.setText("Ver distribución pedidos");
        distribucionPedidosBtt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                distribucionPedidosBtt1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel4))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(distribucionPedidosBtt1)
                            .addComponent(nuncaPedidosBtt1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(118, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(verTopTenBtt1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(33, 33, 33)
                .addComponent(nuncaPedidosBtt1)
                .addGap(29, 29, 29)
                .addComponent(verTopTenBtt1)
                .addGap(18, 18, 18)
                .addComponent(distribucionPedidosBtt1)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pedidosLista.setColumns(20);
        pedidosLista.setRows(5);
        jScrollPane1.setViewportView(pedidosLista);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salirBtt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(cargarPedidosBtt)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(nomUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(salirBtt)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addComponent(cargarPedidosBtt)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eliminarCatalogoBttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarCatalogoBttActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarCatalogoBttActionPerformed

    private void jButtonEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEliminarProductoActionPerformed

    private void cargarPedidosBttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarPedidosBttActionPerformed
        Peticion peticion = new Peticion() ;
        peticion.setAccion(TAccion.VER_PEDIDOS);
        Cliente miCliente = new Cliente(peticion);
        String respuestaServer = (String) miCliente.getRespuestaServer();
        pedidosLista.setText(respuestaServer + '\n');
    }//GEN-LAST:event_cargarPedidosBttActionPerformed

    private void distribucionPedidosBtt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_distribucionPedidosBtt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_distribucionPedidosBtt1ActionPerformed

    private void salirBttMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirBttMouseClicked
            FrmInicio salir = new FrmInicio();
            salir.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_salirBttMouseClicked

    private void agregarProductoBttMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarProductoBttMouseClicked
            FrmAgregarProducto agregarProducto = new FrmAgregarProducto();
            agregarProducto.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_agregarProductoBttMouseClicked

    private void salirBttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirBttActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salirBttActionPerformed

    private void agregarProductoBttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarProductoBttActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarProductoBttActionPerformed

    private void modificarProductoBttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarProductoBttActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modificarProductoBttActionPerformed

    private void eliminarCatalogoBttMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarCatalogoBttMouseClicked
        FrmEliminarCatalogo eliminarCatalogo = new FrmEliminarCatalogo();
        eliminarCatalogo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_eliminarCatalogoBttMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPantallaPrincipalAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPantallaPrincipalAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPantallaPrincipalAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPantallaPrincipalAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPantallaPrincipalAdm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarProductoBtt;
    private javax.swing.JButton cargarPedidosBtt;
    private javax.swing.JButton distribucionPedidosBtt1;
    private javax.swing.JButton eliminarCatalogoBtt;
    private javax.swing.JButton jButtonAgregarProducto;
    private javax.swing.JButton jButtonEliminarProducto;
    private javax.swing.JButton jButtonModificarProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modificarProductoBtt;
    private javax.swing.JTextField nomUsuario;
    private javax.swing.JButton nuncaPedidosBtt1;
    private javax.swing.JTextArea pedidosLista;
    private javax.swing.JButton salirBtt;
    private javax.swing.JButton verTopTenBtt1;
    // End of variables declaration//GEN-END:variables
}
